export const LOAD_STATUSES = 'LOAD_STATUSES';
export const LOAD_TICKETS = 'LOAD_TICKETS';

export const OPEN_CREATE_TICKET_MODAL = 'OPEN_CREATE_TICKET_MODAL';
export const CLOSE_CREATE_TICKET_MODAL= 'CLOSE_CREATE_TICKET_MODAL';

export const OPEN_DESCRIPTION_MODAL = 'OPEN_DESCRIPTION_MODAL';
export const CLOSE_DESCRIPTION_MODAL= 'CLOSE_DESCRIPTION_MODAL';

export const REQUEST = '_REQUEST';
export const SUCCESS = '_SUCCESS';
export const FAILURE = '_FAILURE';

export const CREATE_TICKET = 'CREATE_TICKET';
export const CHANGE_TICKET_STATUS = 'CHANGE_TICKET_STATUS';
export const DELETE_TICKET = 'DELETE_TICKET';